package cc_harvest;

import cc_harvest.items.ModItems;

import java.util.ArrayList;

import net.minecraft.init.Items;
import net.minecraft.item.Item;

public class ChestItems {
	public ArrayList<Item> itemCrops;
	public ArrayList<Item> itemSeeds;
	public ArrayList<Item> itemTemperateFruits;
	public ArrayList<Item> itemWarmFruits;
	public ArrayList<Item> itemLogFruits;

	public ArrayList<Item> itemTools;
	public ArrayList<Item> itemHoney;
	public ArrayList<Item> itemSoda;
	public ArrayList<Item> itemJuice;
	public ArrayList<Item> itemJelly;
	public ArrayList<Item> itemSmoothie;
	public ArrayList<Item> itemYogurt;
	public ArrayList<Item> itemSandwich;
	public ArrayList<Item> itemSoup;

	public ChestItems() {
		// Crops
		this.itemCrops = new ArrayList<Item>();
		this.itemCrops.add(ModItems.asparagusItem);
		this.itemCrops.add(ModItems.barleyItem);
		this.itemCrops.add(ModItems.beanItem);
		this.itemCrops.add(ModItems.beetItem);
		this.itemCrops.add(ModItems.broccoliItem);
		this.itemCrops.add(ModItems.cauliflowerItem);
		this.itemCrops.add(ModItems.celeryItem);
		this.itemCrops.add(ModItems.cranberryItem);
		this.itemCrops.add(ModItems.garlicItem);
		this.itemCrops.add(ModItems.gingerItem);
		this.itemCrops.add(ModItems.leekItem);
		this.itemCrops.add(ModItems.lettuceItem);
		this.itemCrops.add(ModItems.oatsItem);
		this.itemCrops.add(ModItems.onionItem);
		this.itemCrops.add(ModItems.parsnipItem);
		this.itemCrops.add(ModItems.peanutItem);
		this.itemCrops.add(ModItems.pineappleItem);
		this.itemCrops.add(ModItems.radishItem);
		this.itemCrops.add(ModItems.riceItem);
		this.itemCrops.add(ModItems.rutabagaItem);
		this.itemCrops.add(ModItems.ryeItem);
		this.itemCrops.add(ModItems.scallionItem);
		this.itemCrops.add(ModItems.soybeanItem);
		this.itemCrops.add(ModItems.spiceleafItem);
		this.itemCrops.add(ModItems.sweetPotatoItem);
		this.itemCrops.add(ModItems.teaLeafItem);
		this.itemCrops.add(ModItems.turnipItem);
		this.itemCrops.add(ModItems.whiteMushroomItem);
		this.itemCrops.add(ModItems.artichokeItem);
		this.itemCrops.add(ModItems.bellpepperItem);
		this.itemCrops.add(ModItems.blackberryItem);
		this.itemCrops.add(ModItems.blueberryItem);
		this.itemCrops.add(ModItems.brusselSproutItem);
		this.itemCrops.add(ModItems.cabbageItem);
		this.itemCrops.add(ModItems.cactusFruitItem);
		this.itemCrops.add(ModItems.candleberryItem);
		this.itemCrops.add(ModItems.cantaloupeItem);
		this.itemCrops.add(ModItems.chilipepperItem);
		this.itemCrops.add(ModItems.coffeeBeanItem);
		this.itemCrops.add(ModItems.cornItem);
		this.itemCrops.add(ModItems.cottonItem);
		this.itemCrops.add(ModItems.cucumberItem);
		this.itemCrops.add(ModItems.eggplantItem);
		this.itemCrops.add(ModItems.grapeItem);
		this.itemCrops.add(ModItems.kiwiItem);
		this.itemCrops.add(ModItems.mustardSeedsItem);
		this.itemCrops.add(ModItems.okraItem);
		this.itemCrops.add(ModItems.peasItem);
		this.itemCrops.add(ModItems.raspberryItem);
		this.itemCrops.add(ModItems.rhubarbItem);
		this.itemCrops.add(ModItems.seaweedItem);
		this.itemCrops.add(ModItems.strawberryItem);
		this.itemCrops.add(ModItems.tomatoItem);
		this.itemCrops.add(ModItems.winterSquashItem);
		this.itemCrops.add(ModItems.zucchiniItem);
		this.itemCrops.add(ModItems.bambooShootItem);

		// Seeds
		this.itemSeeds = new ArrayList<Item>();
		this.itemSeeds.add(ModItems.asparagusSeedItem);
		this.itemSeeds.add(ModItems.barleySeedItem);
		this.itemSeeds.add(ModItems.beanSeedItem);
		this.itemSeeds.add(ModItems.beetSeedItem);
		this.itemSeeds.add(ModItems.broccoliSeedItem);
		this.itemSeeds.add(ModItems.cauliflowerSeedItem);
		this.itemSeeds.add(ModItems.celerySeedItem);
		this.itemSeeds.add(ModItems.cranberrySeedItem);
		this.itemSeeds.add(ModItems.garlicSeedItem);
		this.itemSeeds.add(ModItems.gingerSeedItem);
		this.itemSeeds.add(ModItems.leekSeedItem);
		this.itemSeeds.add(ModItems.lettuceSeedItem);
		this.itemSeeds.add(ModItems.oatsSeedItem);
		this.itemSeeds.add(ModItems.onionSeedItem);
		this.itemSeeds.add(ModItems.parsnipSeedItem);
		this.itemSeeds.add(ModItems.peanutSeedItem);
		this.itemSeeds.add(ModItems.pineappleSeedItem);
		this.itemSeeds.add(ModItems.radishSeedItem);
		this.itemSeeds.add(ModItems.riceSeedItem);
		this.itemSeeds.add(ModItems.rutabagaSeedItem);
		this.itemSeeds.add(ModItems.ryeSeedItem);
		this.itemSeeds.add(ModItems.scallionSeedItem);
		this.itemSeeds.add(ModItems.soybeanSeedItem);
		this.itemSeeds.add(ModItems.spiceleafSeedItem);
		this.itemSeeds.add(ModItems.sweetPotatoSeedItem);
		this.itemSeeds.add(ModItems.teaLeafSeedItem);
		this.itemSeeds.add(ModItems.turnipSeedItem);
		this.itemSeeds.add(ModItems.whiteMushroomSeedItem);
		this.itemSeeds.add(ModItems.artichokeSeedItem);
		this.itemSeeds.add(ModItems.bellpepperSeedItem);
		this.itemSeeds.add(ModItems.blackberrySeedItem);
		this.itemSeeds.add(ModItems.blueberrySeedItem);
		this.itemSeeds.add(ModItems.brusselSproutSeedItem);
		this.itemSeeds.add(ModItems.cabbageSeedItem);
		this.itemSeeds.add(ModItems.cactusFruitSeedItem);
		this.itemSeeds.add(ModItems.candleberrySeedItem);
		this.itemSeeds.add(ModItems.cantaloupeSeedItem);
		this.itemSeeds.add(ModItems.chilipepperSeedItem);
		this.itemSeeds.add(ModItems.coffeeBeanSeedItem);
		this.itemSeeds.add(ModItems.cornSeedItem);
		this.itemSeeds.add(ModItems.cottonSeedItem);
		this.itemSeeds.add(ModItems.cucumberSeedItem);
		this.itemSeeds.add(ModItems.eggplantSeedItem);
		this.itemSeeds.add(ModItems.grapeSeedItem);
		this.itemSeeds.add(ModItems.kiwiSeedItem);
		this.itemSeeds.add(ModItems.mustardSeedItem);
		this.itemSeeds.add(ModItems.okraSeedItem);
		this.itemSeeds.add(ModItems.peasSeedItem);
		this.itemSeeds.add(ModItems.raspberrySeedItem);
		this.itemSeeds.add(ModItems.rhubarbSeedItem);
		this.itemSeeds.add(ModItems.seaweedSeedItem);
		this.itemSeeds.add(ModItems.strawberrySeedItem);
		this.itemSeeds.add(ModItems.tomatoSeedItem);
		this.itemSeeds.add(ModItems.winterSquashSeedItem);
		this.itemSeeds.add(ModItems.zucchiniSeedItem);
		this.itemSeeds.add(ModItems.bambooShootSeedItem);

		// Seeds Box
		this.itemSeeds.add(ModItems.asparagusSeedBoxItem);
		this.itemSeeds.add(ModItems.barleySeedBoxItem);
		this.itemSeeds.add(ModItems.beanSeedBoxItem);
		this.itemSeeds.add(ModItems.beetSeedBoxItem);
		this.itemSeeds.add(ModItems.broccoliSeedBoxItem);
		this.itemSeeds.add(ModItems.cauliflowerSeedBoxItem);
		this.itemSeeds.add(ModItems.celerySeedBoxItem);
		this.itemSeeds.add(ModItems.cranberrySeedBoxItem);
		this.itemSeeds.add(ModItems.garlicSeedBoxItem);
		this.itemSeeds.add(ModItems.gingerSeedBoxItem);
		this.itemSeeds.add(ModItems.leekSeedBoxItem);
		this.itemSeeds.add(ModItems.lettuceSeedBoxItem);
		this.itemSeeds.add(ModItems.oatsSeedBoxItem);
		this.itemSeeds.add(ModItems.onionSeedBoxItem);
		this.itemSeeds.add(ModItems.parsnipSeedBoxItem);
		this.itemSeeds.add(ModItems.peanutSeedBoxItem);
		this.itemSeeds.add(ModItems.pineappleSeedBoxItem);
		this.itemSeeds.add(ModItems.radishSeedBoxItem);
		this.itemSeeds.add(ModItems.riceSeedBoxItem);
		this.itemSeeds.add(ModItems.rutabagaSeedBoxItem);
		this.itemSeeds.add(ModItems.ryeSeedBoxItem);
		this.itemSeeds.add(ModItems.scallionSeedBoxItem);
		this.itemSeeds.add(ModItems.soybeanSeedBoxItem);
		this.itemSeeds.add(ModItems.spiceleafSeedBoxItem);
		this.itemSeeds.add(ModItems.sweetPotatoSeedBoxItem);
		this.itemSeeds.add(ModItems.teaSeedBoxItem);
		this.itemSeeds.add(ModItems.turnipSeedBoxItem);
		this.itemSeeds.add(ModItems.whiteMushroomSeedBoxItem);
		this.itemSeeds.add(ModItems.artichokeSeedBoxItem);
		this.itemSeeds.add(ModItems.bellpepperSeedBoxItem);
		this.itemSeeds.add(ModItems.blackberrySeedBoxItem);
		this.itemSeeds.add(ModItems.blueberrySeedBoxItem);
		this.itemSeeds.add(ModItems.brusselSproutSeedBoxItem);
		this.itemSeeds.add(ModItems.cabbageSeedBoxItem);
		this.itemSeeds.add(ModItems.cactusFruitSeedBoxItem);
		this.itemSeeds.add(ModItems.candleberrySeedBoxItem);
		this.itemSeeds.add(ModItems.cantaloupeSeedBoxItem);
		this.itemSeeds.add(ModItems.chilipepperSeedBoxItem);
		this.itemSeeds.add(ModItems.coffeeSeedBoxItem);
		this.itemSeeds.add(ModItems.cornSeedBoxItem);
		this.itemSeeds.add(ModItems.cottonSeedBoxItem);
		this.itemSeeds.add(ModItems.cucumberSeedBoxItem);
		this.itemSeeds.add(ModItems.eggplantSeedBoxItem);
		this.itemSeeds.add(ModItems.grapeSeedBoxItem);
		this.itemSeeds.add(ModItems.kiwiSeedBoxItem);
		this.itemSeeds.add(ModItems.mustardSeedBoxItem);
		this.itemSeeds.add(ModItems.okraSeedBoxItem);
		this.itemSeeds.add(ModItems.peasSeedBoxItem);
		this.itemSeeds.add(ModItems.raspberrySeedBoxItem);
		this.itemSeeds.add(ModItems.rhubarbSeedBoxItem);
		this.itemSeeds.add(ModItems.seaweedSeedBoxItem);
		this.itemSeeds.add(ModItems.strawberrySeedBoxItem);
		this.itemSeeds.add(ModItems.tomatoSeedBoxItem);
		this.itemSeeds.add(ModItems.winterSquashSeedBoxItem);
		this.itemSeeds.add(ModItems.zucchiniSeedBoxItem);
		this.itemSeeds.add(ModItems.bambooShootSeedBoxItem);

		// Seeds Packet
		this.itemSeeds.add(ModItems.asparagusSeedPacketItem);
		this.itemSeeds.add(ModItems.barleySeedPacketItem);
		this.itemSeeds.add(ModItems.beanSeedPacketItem);
		this.itemSeeds.add(ModItems.beetSeedPacketItem);
		this.itemSeeds.add(ModItems.broccoliSeedPacketItem);
		this.itemSeeds.add(ModItems.cauliflowerSeedPacketItem);
		this.itemSeeds.add(ModItems.celerySeedPacketItem);
		this.itemSeeds.add(ModItems.cranberrySeedPacketItem);
		this.itemSeeds.add(ModItems.garlicSeedPacketItem);
		this.itemSeeds.add(ModItems.gingerSeedPacketItem);
		this.itemSeeds.add(ModItems.leekSeedPacketItem);
		this.itemSeeds.add(ModItems.lettuceSeedPacketItem);
		this.itemSeeds.add(ModItems.oatsSeedPacketItem);
		this.itemSeeds.add(ModItems.onionSeedPacketItem);
		this.itemSeeds.add(ModItems.parsnipSeedPacketItem);
		this.itemSeeds.add(ModItems.peanutSeedPacketItem);
		this.itemSeeds.add(ModItems.pineappleSeedPacketItem);
		this.itemSeeds.add(ModItems.radishSeedPacketItem);
		this.itemSeeds.add(ModItems.riceSeedPacketItem);
		this.itemSeeds.add(ModItems.rutabagaSeedPacketItem);
		this.itemSeeds.add(ModItems.ryeSeedPacketItem);
		this.itemSeeds.add(ModItems.scallionSeedPacketItem);
		this.itemSeeds.add(ModItems.soybeanSeedPacketItem);
		this.itemSeeds.add(ModItems.spiceleafSeedPacketItem);
		this.itemSeeds.add(ModItems.sweetPotatoSeedPacketItem);
		this.itemSeeds.add(ModItems.teaSeedPacketItem);
		this.itemSeeds.add(ModItems.turnipSeedPacketItem);
		this.itemSeeds.add(ModItems.whiteMushroomSeedPacketItem);
		this.itemSeeds.add(ModItems.artichokeSeedPacketItem);
		this.itemSeeds.add(ModItems.bellpepperSeedPacketItem);
		this.itemSeeds.add(ModItems.blackberrySeedPacketItem);
		this.itemSeeds.add(ModItems.blueberrySeedPacketItem);
		this.itemSeeds.add(ModItems.brusselSproutSeedPacketItem);
		this.itemSeeds.add(ModItems.cabbageSeedPacketItem);
		this.itemSeeds.add(ModItems.cactusFruitSeedPacketItem);
		this.itemSeeds.add(ModItems.candleberrySeedPacketItem);
		this.itemSeeds.add(ModItems.cantaloupeSeedPacketItem);
		this.itemSeeds.add(ModItems.chilipepperSeedPacketItem);
		this.itemSeeds.add(ModItems.coffeeSeedPacketItem);
		this.itemSeeds.add(ModItems.cornSeedPacketItem);
		this.itemSeeds.add(ModItems.cottonSeedPacketItem);
		this.itemSeeds.add(ModItems.cucumberSeedPacketItem);
		this.itemSeeds.add(ModItems.eggplantSeedPacketItem);
		this.itemSeeds.add(ModItems.grapeSeedPacketItem);
		this.itemSeeds.add(ModItems.kiwiSeedPacketItem);
		this.itemSeeds.add(ModItems.mustardSeedPacketItem);
		this.itemSeeds.add(ModItems.okraSeedPacketItem);
		this.itemSeeds.add(ModItems.peasSeedPacketItem);
		this.itemSeeds.add(ModItems.raspberrySeedPacketItem);
		this.itemSeeds.add(ModItems.rhubarbSeedPacketItem);
		this.itemSeeds.add(ModItems.seaweedSeedPacketItem);
		this.itemSeeds.add(ModItems.strawberrySeedPacketItem);
		this.itemSeeds.add(ModItems.tomatoSeedPacketItem);
		this.itemSeeds.add(ModItems.winterSquashSeedPacketItem);
		this.itemSeeds.add(ModItems.zucchiniSeedPacketItem);
		this.itemSeeds.add(ModItems.bambooShootSeedPacketItem);

		// Temperate Fruits
		this.itemTemperateFruits = new ArrayList<Item>();
		this.itemTemperateFruits.add(Items.apple);
		this.itemTemperateFruits.add(ModItems.avocadoItem);
		this.itemTemperateFruits.add(ModItems.cherryItem);
		this.itemTemperateFruits.add(ModItems.chestnutItem);
		this.itemTemperateFruits.add(ModItems.nutmegItem);
		this.itemTemperateFruits.add(ModItems.pearItem);
		this.itemTemperateFruits.add(ModItems.plumItem);
		this.itemTemperateFruits.add(ModItems.walnutItem);

		// Warm Fruits
		this.itemWarmFruits = new ArrayList<Item>();
		this.itemWarmFruits.add(ModItems.almondItem);
		this.itemWarmFruits.add(ModItems.apricotItem);
		this.itemWarmFruits.add(ModItems.bananaItem);
		this.itemWarmFruits.add(ModItems.cashewItem);
		this.itemWarmFruits.add(ModItems.coconutItem);
		this.itemWarmFruits.add(ModItems.dateItem);
		this.itemWarmFruits.add(ModItems.dragonfruitItem);
		this.itemWarmFruits.add(ModItems.durianItem);
		this.itemWarmFruits.add(ModItems.figItem);
		this.itemWarmFruits.add(ModItems.grapefruitItem);
		this.itemWarmFruits.add(ModItems.lemonItem);
		this.itemWarmFruits.add(ModItems.limeItem);
		this.itemWarmFruits.add(ModItems.mangoItem);
		this.itemWarmFruits.add(ModItems.oliveItem);
		this.itemWarmFruits.add(ModItems.orangeItem);
		this.itemWarmFruits.add(ModItems.papayaItem);
		this.itemWarmFruits.add(ModItems.peachItem);
		this.itemWarmFruits.add(ModItems.pecanItem);
		this.itemWarmFruits.add(ModItems.peppercornItem);
		this.itemWarmFruits.add(ModItems.persimmonItem);
		this.itemWarmFruits.add(ModItems.pistachioItem);
		this.itemWarmFruits.add(ModItems.pomegranateItem);
		this.itemWarmFruits.add(ModItems.starfruitItem);
		this.itemWarmFruits.add(ModItems.vanillaBeanItem);

		// Log Fruits
		this.itemLogFruits = new ArrayList<Item>();
		this.itemLogFruits.add(ModItems.cinnamonItem);
		this.itemLogFruits.add(ModItems.mapleSyrupItem);
		this.itemLogFruits.add(Items.paper);
		this.itemLogFruits.add(ModItems.beeswaxItem);
		this.itemLogFruits.add(ModItems.grubItem);
		this.itemLogFruits.add(ModItems.honeycombItem);
		this.itemLogFruits.add(ModItems.honeyItem);
		this.itemLogFruits.add(ModItems.queenBeeItem);
		this.itemLogFruits.add(ModItems.royalJellyItem);
		this.itemLogFruits.add(ModItems.waxcombItem);

		// Tools
		this.itemTools = new ArrayList<Item>();
		this.itemTools.add(ModItems.bakewareItem);
		this.itemTools.add(ModItems.cuttingboardItem);
		this.itemTools.add(ModItems.juicerItem);
		this.itemTools.add(ModItems.mixingBowlItem);
		this.itemTools.add(ModItems.mortarAndPestleItem);
		this.itemTools.add(ModItems.potItem);
		this.itemTools.add(ModItems.saucepanItem);
		this.itemTools.add(ModItems.skilletItem);

		// Honey
		this.itemHoney = new ArrayList<Item>();
		this.itemHoney.add(ModItems.beeswaxItem);
		this.itemHoney.add(ModItems.waxItem);
		this.itemHoney.add(ModItems.grubItem);
		this.itemHoney.add(ModItems.honeycombItem);
		this.itemHoney.add(ModItems.honeyItem);
		this.itemHoney.add(ModItems.queenBeeItem);
		this.itemHoney.add(ModItems.royalJellyItem);
		this.itemHoney.add(ModItems.waxcombItem);

		// Soda
		this.itemSoda = new ArrayList<Item>();
		this.itemSoda.add(ModItems.cherrySodaItem);
		this.itemSoda.add(ModItems.colaSodaItem);
		this.itemSoda.add(ModItems.gingerSodaItem);
		this.itemSoda.add(ModItems.grapeSodaItem);
		this.itemSoda.add(ModItems.lemonLimeSodaItem);
		this.itemSoda.add(ModItems.orangeSodaItem);
		this.itemSoda.add(ModItems.rootbeerSodaItem);
		this.itemSoda.add(ModItems.strawberrySodaItem);
		this.itemSoda.add(ModItems.grapefruitSodaItem);

		// Juice
		this.itemJuice = new ArrayList<Item>();
		this.itemJuice.add(ModItems.appleJuiceItem);
		this.itemJuice.add(ModItems.apricotJuiceItem);
		this.itemJuice.add(ModItems.blackberryJuiceItem);
		this.itemJuice.add(ModItems.blueberryJuiceItem);
		this.itemJuice.add(ModItems.cactusFruitJuiceItem);
		this.itemJuice.add(ModItems.carrotJuiceItem);
		this.itemJuice.add(ModItems.cherryJuiceItem);
		this.itemJuice.add(ModItems.cranberryJuiceItem);
		this.itemJuice.add(ModItems.figJuiceItem);
		this.itemJuice.add(ModItems.grapefruitJuiceItem);
		this.itemJuice.add(ModItems.grapeJuiceItem);
		this.itemJuice.add(ModItems.kiwiJuiceItem);
		this.itemJuice.add(ModItems.limeJuiceItem);
		this.itemJuice.add(ModItems.mangoJuiceItem);
		this.itemJuice.add(ModItems.melonJuiceItem);
		this.itemJuice.add(ModItems.orangeJuiceItem);
		this.itemJuice.add(ModItems.papayaJuiceItem);
		this.itemJuice.add(ModItems.peachJuiceItem);
		this.itemJuice.add(ModItems.pearJuiceItem);
		this.itemJuice.add(ModItems.persimmonJuiceItem);
		this.itemJuice.add(ModItems.plumJuiceItem);
		this.itemJuice.add(ModItems.pomegranateJuiceItem);
		this.itemJuice.add(ModItems.raspberryJuiceItem);
		this.itemJuice.add(ModItems.starfruitJuiceItem);
		this.itemJuice.add(ModItems.strawberryJuiceItem);

		// Jelly
		this.itemJelly = new ArrayList<Item>();
		this.itemJelly.add(ModItems.appleJellyItem);
		this.itemJelly.add(ModItems.apricotJellyItem);
		this.itemJelly.add(ModItems.blackberryJellyItem);
		this.itemJelly.add(ModItems.blueberryJellyItem);
		this.itemJelly.add(ModItems.cherryJellyItem);
		this.itemJelly.add(ModItems.cranberryJellyItem);
		this.itemJelly.add(ModItems.figJellyItem);
		this.itemJelly.add(ModItems.grapefruitJellyItem);
		this.itemJelly.add(ModItems.grapeJellyItem);
		this.itemJelly.add(ModItems.kiwiJellyItem);
		this.itemJelly.add(ModItems.lemonJellyItem);
		this.itemJelly.add(ModItems.limeJellyItem);
		this.itemJelly.add(ModItems.mangoJellyItem);
		this.itemJelly.add(ModItems.orangeJellyItem);
		this.itemJelly.add(ModItems.papayaJellyItem);
		this.itemJelly.add(ModItems.peachJellyItem);
		this.itemJelly.add(ModItems.persimmonJellyItem);
		this.itemJelly.add(ModItems.pomegranateJellyItem);
		this.itemJelly.add(ModItems.raspberryJellyItem);
		this.itemJelly.add(ModItems.starfruitJellyItem);
		this.itemJelly.add(ModItems.strawberryJellyItem);
		this.itemJelly.add(ModItems.watermelonJellyItem);

		// Smoothie
		this.itemSmoothie = new ArrayList<Item>();
		this.itemSmoothie.add(ModItems.apricotSmoothieItem);
		this.itemSmoothie.add(ModItems.bananaSmoothieItem);
		this.itemSmoothie.add(ModItems.blackberrySmoothieItem);
		this.itemSmoothie.add(ModItems.blueberrySmoothieItem);
		this.itemSmoothie.add(ModItems.cherrySmoothieItem);
		this.itemSmoothie.add(ModItems.figSmoothieItem);
		this.itemSmoothie.add(ModItems.grapefruitSmoothieItem);
		this.itemSmoothie.add(ModItems.kiwiSmoothieItem);
		this.itemSmoothie.add(ModItems.lemonSmoothieItem);
		this.itemSmoothie.add(ModItems.limeSmoothieItem);
		this.itemSmoothie.add(ModItems.mangoSmoothieItem);
		this.itemSmoothie.add(ModItems.melonSmoothieItem);
		this.itemSmoothie.add(ModItems.orangeSmoothieItem);
		this.itemSmoothie.add(ModItems.papayaSmoothieItem);
		this.itemSmoothie.add(ModItems.peachSmoothieItem);
		this.itemSmoothie.add(ModItems.persimmonSmoothieItem);
		this.itemSmoothie.add(ModItems.pomegranateSmoothieItem);
		this.itemSmoothie.add(ModItems.raspberrySmoothieItem);
		this.itemSmoothie.add(ModItems.starfruitSmoothieItem);
		this.itemSmoothie.add(ModItems.strawberrySmoothieItem);

		// Yogurt
		this.itemYogurt = new ArrayList<Item>();
		this.itemYogurt.add(ModItems.appleYogurtItem);
		this.itemYogurt.add(ModItems.apricotYogurtItem);
		this.itemYogurt.add(ModItems.bananaYogurtItem);
		this.itemYogurt.add(ModItems.blackberryYogurtItem);
		this.itemYogurt.add(ModItems.blueberryYogurtItem);
		this.itemYogurt.add(ModItems.cherryYogurtItem);
		this.itemYogurt.add(ModItems.chocolateYogurtItem);
		this.itemYogurt.add(ModItems.coconutYogurtItem);
		this.itemYogurt.add(ModItems.figYogurtItem);
		this.itemYogurt.add(ModItems.grapefruitYogurtItem);
		this.itemYogurt.add(ModItems.grapeYogurtItem);
		this.itemYogurt.add(ModItems.kiwiYogurtItem);
		this.itemYogurt.add(ModItems.lemonYogurtItem);
		this.itemYogurt.add(ModItems.limeYogurtItem);
		this.itemYogurt.add(ModItems.mangoYogurtItem);
		this.itemYogurt.add(ModItems.melonYogurtItem);
		this.itemYogurt.add(ModItems.orangeYogurtItem);
		this.itemYogurt.add(ModItems.papayaYogurtItem);
		this.itemYogurt.add(ModItems.peachYogurtItem);
		this.itemYogurt.add(ModItems.pearYogurtItem);
		this.itemYogurt.add(ModItems.persimmonYogurtItem);
		this.itemYogurt.add(ModItems.pineappleYogurtItem);
		this.itemYogurt.add(ModItems.plainYogurtItem);
		this.itemYogurt.add(ModItems.plumYogurtItem);
		this.itemYogurt.add(ModItems.pomegranateYogurtItem);
		this.itemYogurt.add(ModItems.pumpkinYogurtItem);
		this.itemYogurt.add(ModItems.raspberryYogurtItem);
		this.itemYogurt.add(ModItems.starfruitYogurtItem);
		this.itemYogurt.add(ModItems.strawberryYogurtItem);
		this.itemYogurt.add(ModItems.vanillaYogurtItem);

		// Sandwich
		this.itemSandwich = new ArrayList<Item>();
		this.itemSandwich.add(ModItems.chickenSandwichItem);
		this.itemSandwich.add(ModItems.fishSandwichItem);
		this.itemSandwich.add(ModItems.leafyChickenSandwichItem);
		this.itemSandwich.add(ModItems.leafyFishSandwichItem);
		this.itemSandwich.add(ModItems.toastSandwichItem);

		this.itemSandwich.add(ModItems.appleJellySandwichItem);
		this.itemSandwich.add(ModItems.apricotJellySandwichItem);
		this.itemSandwich.add(ModItems.blackberryJellySandwichItem);
		this.itemSandwich.add(ModItems.blueberryJellySandwichItem);
		this.itemSandwich.add(ModItems.cherryJellySandwichItem);
		this.itemSandwich.add(ModItems.cranberryJellySandwichItem);
		this.itemSandwich.add(ModItems.figJellySandwichItem);
		this.itemSandwich.add(ModItems.grapefruitJellySandwichItem);
		this.itemSandwich.add(ModItems.kiwiJellySandwichItem);
		this.itemSandwich.add(ModItems.lemonJellySandwichItem);
		this.itemSandwich.add(ModItems.limeJellySandwichItem);
		this.itemSandwich.add(ModItems.mangoJellySandwichItem);
		this.itemSandwich.add(ModItems.orangeJellySandwichItem);
		this.itemSandwich.add(ModItems.papayaJellySandwichItem);
		this.itemSandwich.add(ModItems.peachJellySandwichItem);
		this.itemSandwich.add(ModItems.persimmonJellySandwichItem);
		this.itemSandwich.add(ModItems.pomegranateJellySandwichItem);
		this.itemSandwich.add(ModItems.raspberryJellySandwichItem);
		this.itemSandwich.add(ModItems.starfruitJellySandwichItem);
		this.itemSandwich.add(ModItems.strawberryJellySandwichItem);
		this.itemSandwich.add(ModItems.watermelonJellySandwichItem);

		// Soup
		this.itemSoup = new ArrayList<Item>();
		this.itemSoup.add(ModItems.asparagusSoupItem);
		this.itemSoup.add(ModItems.beetSoupItem);
		this.itemSoup.add(ModItems.cactusSoupItem);
		this.itemSoup.add(ModItems.carrotSoupItem);
		this.itemSoup.add(ModItems.celerySoupItem);
		this.itemSoup.add(ModItems.chickenNoodleSoupItem);
		this.itemSoup.add(ModItems.creamedBroccoliSoupItem);
		this.itemSoup.add(ModItems.creamOfAvocadoSoupItem);
		this.itemSoup.add(ModItems.cucumberSoupItem);
		this.itemSoup.add(ModItems.gardenSoupItem);
		this.itemSoup.add(ModItems.lambBarleySoupItem);
		this.itemSoup.add(ModItems.leekBaconSoupItem);
		this.itemSoup.add(ModItems.oldWorldVeggieSoupItem);
		this.itemSoup.add(ModItems.onionSoupItem);
		this.itemSoup.add(ModItems.potatoSoupItem);
		this.itemSoup.add(ModItems.pumpkinSoupItem);
		this.itemSoup.add(ModItems.riceSoupItem);
		this.itemSoup.add(ModItems.seedSoupItem);
		this.itemSoup.add(ModItems.spiderEyeSoupItem);
		this.itemSoup.add(ModItems.splitPeaSoupItem);
		this.itemSoup.add(ModItems.tomatoSoupItem);
		this.itemSoup.add(ModItems.turnipSoupItem);
		this.itemSoup.add(ModItems.vegetableSoupItem);
	}
}
