package cc_harvest.blocks;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModBlocks {
	public static Block[] temperateSaplings;
	public static Block[] warmSaplings;
	public static Block[] logSaplings;

	// Tools
	public static BlockCuttingBoard cuttingBoard;
	public static BlockPot pot;
	public static BlockApiary apiary;
	public static BlockPresser presser;
	public static BlockChurn churn;
	public static BlockQuern quern;
	public static BlockSink sinkWood;
	public static BlockSink sinkStone;
	public static BlockSink sinkClay;
	public static BlockSink sinkBrick;

	// Storage
	public static BlockStorageBox storageCropsBox;
	public static BlockStorageBox storageSeedsBox;
	public static BlockStorageBox storageTemperateFruitsBox;
	public static BlockStorageBox storageWarmFruitsBox;
	public static BlockStorageBox storageLogFruitsBox;

	public static BlockStorageBox storageCakeBox;
	public static BlockStorageBox storageHoneyBox;
	public static BlockStorageBox storageJellyBox;
	public static BlockStorageBox storageJuiceBox;
	public static BlockStorageBox storagePieBox;
	public static BlockStorageBox storageSaladBox;
	public static BlockStorageBox storageSandwichBox;
	public static BlockStorageBox storageSmoothieBox;
	public static BlockStorageBox storageSodaBox;
	public static BlockStorageBox storageSoupBox;
	public static BlockStorageBox storageToolsBox;
	public static BlockStorageBox storageYogurtBox;

	// Ground
	public static BlockSalt salt;
	public static BlockBeehive beehive;

	// Garden
	public static BlockNormalGarden berryGarden;
	public static BlockDesertGarden desertGarden;
	public static BlockNormalGarden grassGarden;
	public static BlockNormalGarden gourdGarden;
	public static BlockNormalGarden groundGarden;
	public static BlockNormalGarden herbGarden;
	public static BlockNormalGarden leafyGarden;
	public static BlockMushroomGarden mushroomGarden;
	public static BlockNormalGarden stalkGarden;
	public static BlockNormalGarden textileGarden;
	public static BlockNormalGarden tropicalGarden;
	public static BlockWaterGarden waterGarden;

	// Food
	public static BlockFruit apple;
	public static BlockFruit almond;
	public static BlockFruit apricot;
	public static BlockFruit avocado;
	public static BlockFruit banana;
	public static BlockFruit cashew;
	public static BlockFruit cherry;
	public static BlockFruit chestnut;
	public static BlockFruitTree cinnamon;
	public static BlockFruit coconut;
	public static BlockFruit date;
	public static BlockFruit dragonfruit;
	public static BlockFruit durian;
	public static BlockFruit fig;
	public static BlockFruit grapefruit;
	public static BlockFruit lemon;
	public static BlockFruit lime;
	public static BlockFruitTree maple;
	public static BlockFruit mango;
	public static BlockFruit nutmeg;
	public static BlockFruit olive;
	public static BlockFruit orange;
	public static BlockFruit papaya;
	public static BlockFruitTree paperbark;
	public static BlockFruit peach;
	public static BlockFruit pear;
	public static BlockFruit pecan;
	public static BlockFruit peppercorn;
	public static BlockFruit persimmon;
	public static BlockFruit pistachio;
	public static BlockFruit plum;
	public static BlockFruit pomegranate;
	public static BlockFruit starfruit;
	public static BlockFruit vanillaBean;
	public static BlockFruit walnut;

	// Sapling
	public static BlockSapling appleSapling;
	public static BlockSapling almondSapling;
	public static BlockSapling apricotSapling;
	public static BlockSapling avocadoSapling;
	public static BlockSapling bananaSapling;
	public static BlockSapling cashewSapling;
	public static BlockSapling cherrySapling;
	public static BlockSapling chestnutSapling;
	public static BlockSapling cinnamonSapling;
	public static BlockSapling coconutSapling;
	public static BlockSapling dateSapling;
	public static BlockSapling dragonfruitSapling;
	public static BlockSapling durianSapling;
	public static BlockSapling figSapling;
	public static BlockSapling grapefruitSapling;
	public static BlockSapling lemonSapling;
	public static BlockSapling limeSapling;
	public static BlockSapling mapleSapling;
	public static BlockSapling mangoSapling;
	public static BlockSapling nutmegSapling;
	public static BlockSapling oliveSapling;
	public static BlockSapling orangeSapling;
	public static BlockSapling papayaSapling;
	public static BlockSapling paperbarkSapling;
	public static BlockSapling peachSapling;
	public static BlockSapling pearSapling;
	public static BlockSapling pecanSapling;
	public static BlockSapling peppercornSapling;
	public static BlockSapling persimmonSapling;
	public static BlockSapling pistachioSapling;
	public static BlockSapling plumSapling;
	public static BlockSapling pomegranateSapling;
	public static BlockSapling starfruitSapling;
	public static BlockSapling vanillaBeanSapling;
	public static BlockSapling walnutSapling;

	// Crop
	public static BlockCrop artichokeCrop;
	public static BlockCrop asparagusCrop;
	public static BlockCrop bambooShootCrop;
	public static BlockCrop barleyCrop;
	public static BlockCrop beanCrop;
	public static BlockCrop beetCrop;
	public static BlockCrop bellpepperCrop;
	public static BlockCrop blackberryCrop;
	public static BlockCrop blueberryCrop;
	public static BlockCrop broccoliCrop;
	public static BlockCrop brusselSproutCrop;
	public static BlockCrop cabbageCrop;
	public static BlockCrop cactusFruitCrop;
	public static BlockCrop candleberryCrop;
	public static BlockCrop cantaloupeCrop;
	public static BlockCrop cauliflowerCrop;
	public static BlockCrop celeryCrop;
	public static BlockCrop chilipepperCrop;
	public static BlockCrop coffeeBeanCrop;
	public static BlockCrop cornCrop;
	public static BlockCrop cottonCrop;
	public static BlockCrop cranberryCrop;
	public static BlockCrop cucumberCrop;
	public static BlockCrop eggplantCrop;
	public static BlockCrop garlicCrop;
	public static BlockCrop gingerCrop;
	public static BlockCrop grapeCrop;
	public static BlockCrop kiwiCrop;
	public static BlockCrop leekCrop;
	public static BlockCrop lettuceCrop;
	public static BlockCrop mustardSeedsCrop;
	public static BlockCrop oatsCrop;
	public static BlockCrop okraCrop;
	public static BlockCrop onionCrop;
	public static BlockCrop parsnipCrop;
	public static BlockCrop peanutCrop;
	public static BlockCrop peasCrop;
	public static BlockCrop pineappleCrop;
	public static BlockCrop radishCrop;
	public static BlockCrop raspberryCrop;
	public static BlockCrop rhubarbCrop;
	public static BlockCrop riceCrop;
	public static BlockCrop rutabagaCrop;
	public static BlockCrop ryeCrop;
	public static BlockCrop scallionCrop;
	public static BlockCrop seaweedCrop;
	public static BlockCrop soybeanCrop;
	public static BlockCrop spiceLeafCrop;
	public static BlockCrop strawberryCrop;
	public static BlockCrop sweetPotatoCrop;
	public static BlockCrop teaLeafCrop;
	public static BlockCrop tomatoCrop;
	public static BlockCrop turnipCrop;
	public static BlockCrop whiteMushroomCrop;
	public static BlockCrop winterSquashCrop;
	public static BlockCrop zucchiniCrop;

	// Candle
	public static BlockCandle candle_0;
	public static BlockCandle candle_1;
	public static BlockCandle candle_2;
	public static BlockCandle candle_3;
	public static BlockCandle candle_4;
	public static BlockCandle candle_5;
	public static BlockCandle candle_6;
	public static BlockCandle candle_7;
	public static BlockCandle candle_8;
	public static BlockCandle candle_9;
	public static BlockCandle candle_10;
	public static BlockCandle candle_11;
	public static BlockCandle candle_12;
	public static BlockCandle candle_13;
	public static BlockCandle candle_14;
	public static BlockCandle candle_15;

	public static void main() {
		// Tools
		cuttingBoard = new BlockCuttingBoard("cuttingBoard");
		pot = new BlockPot("pot");
		apiary = new BlockApiary("apiary");
		presser = new BlockPresser("presser");
		churn = new BlockChurn("churn");
		quern = new BlockQuern("quern");
		sinkWood = new BlockSink("sinkWood");
		sinkStone = new BlockSink("sinkStone");
		sinkClay = new BlockSink("sinkClay");
		sinkBrick = new BlockSink("sinkBrick");

		ModBlocks.registerBlock(cuttingBoard);
		ModBlocks.registerBlock(pot);
		ModBlocks.registerBlock(apiary);
		ModBlocks.registerBlock(presser);
		ModBlocks.registerBlock(churn);
		ModBlocks.registerBlock(quern);
		ModBlocks.registerBlock(sinkWood);
		ModBlocks.registerBlock(sinkStone);
		ModBlocks.registerBlock(sinkClay);
		ModBlocks.registerBlock(sinkBrick);

		// Storage
		storageCropsBox = new BlockStorageBox("storageCropsBox");
		storageSeedsBox = new BlockStorageBox("storageSeedsBox");
		storageTemperateFruitsBox = new BlockStorageBox("storageTemperateFruitsBox");
		storageWarmFruitsBox = new BlockStorageBox("storageWarmFruitsBox");
		storageLogFruitsBox = new BlockStorageBox("storageLogFruitsBox");

		ModBlocks.registerBlock(storageCropsBox);
		ModBlocks.registerBlock(storageSeedsBox);
		ModBlocks.registerBlock(storageTemperateFruitsBox);
		ModBlocks.registerBlock(storageWarmFruitsBox);
		ModBlocks.registerBlock(storageLogFruitsBox);

		storageCakeBox = new BlockStorageBox("storageCakeBox");
		storageHoneyBox = new BlockStorageBox("storageHoneyBox");
		storageJellyBox = new BlockStorageBox("storageJellyBox");
		storageJuiceBox = new BlockStorageBox("storageJuiceBox");
		storagePieBox = new BlockStorageBox("storagePieBox");
		storageSaladBox = new BlockStorageBox("storageSaladBox");
		storageSandwichBox = new BlockStorageBox("storageSandwichBox");
		storageSmoothieBox = new BlockStorageBox("storageSmoothieBox");
		storageSodaBox = new BlockStorageBox("storageSodaBox");
		storageSoupBox = new BlockStorageBox("storageSoupBox");
		storageToolsBox = new BlockStorageBox("storageToolsBox");
		storageYogurtBox = new BlockStorageBox("storageYogurtBox");

		ModBlocks.registerBlock(storageCakeBox);
		ModBlocks.registerBlock(storageHoneyBox);
		ModBlocks.registerBlock(storageJellyBox);
		ModBlocks.registerBlock(storageJuiceBox);
		ModBlocks.registerBlock(storagePieBox);
		ModBlocks.registerBlock(storageSaladBox);
		ModBlocks.registerBlock(storageSandwichBox);
		ModBlocks.registerBlock(storageSmoothieBox);
		ModBlocks.registerBlock(storageSodaBox);
		ModBlocks.registerBlock(storageSoupBox);
		ModBlocks.registerBlock(storageToolsBox);
		ModBlocks.registerBlock(storageYogurtBox);

		// Ground
		salt = new BlockSalt("salt");
		beehive = new BlockBeehive(Material.plants, "beehive");

		ModBlocks.registerBlock(salt);
		ModBlocks.registerBlock(beehive);

		// Garden
		berryGarden = new BlockNormalGarden("berryGarden");
		desertGarden = new BlockDesertGarden("desertGarden");
		grassGarden = new BlockNormalGarden("grassGarden");
		gourdGarden = new BlockNormalGarden("gourdGarden");
		groundGarden = new BlockNormalGarden("groundGarden");
		herbGarden = new BlockNormalGarden("herbGarden");
		leafyGarden = new BlockNormalGarden("leafyGarden");
		mushroomGarden = new BlockMushroomGarden("mushroomGarden");
		stalkGarden = new BlockNormalGarden("stalkGarden");
		textileGarden = new BlockNormalGarden("textileGarden");
		tropicalGarden = new BlockNormalGarden("tropicalGarden");
		waterGarden = new BlockWaterGarden("waterGarden");

		ModBlocks.registerBlock(berryGarden);
		ModBlocks.registerBlock(desertGarden);
		ModBlocks.registerBlock(grassGarden);
		ModBlocks.registerBlock(gourdGarden);
		ModBlocks.registerBlock(groundGarden);
		ModBlocks.registerBlock(herbGarden);
		ModBlocks.registerBlock(leafyGarden);
		ModBlocks.registerBlock(mushroomGarden);
		ModBlocks.registerBlock(stalkGarden);
		ModBlocks.registerBlock(textileGarden);
		ModBlocks.registerBlock(tropicalGarden);
		ModBlocks.registerBlock(waterGarden);

		// Food
		apple = new BlockFruit("apple");
		almond = new BlockFruit("almond");
		apricot = new BlockFruit("apricot");
		avocado = new BlockFruit("avocado");
		banana = new BlockFruit("banana");
		cashew = new BlockFruit("cashew");
		cherry = new BlockFruit("cherry");
		chestnut = new BlockFruit("chestnut");
		cinnamon = new BlockFruitTree("cinnamon");
		coconut = new BlockFruit("coconut");
		date = new BlockFruit("date");
		dragonfruit = new BlockFruit("dragonfruit");
		durian = new BlockFruit("durian");
		fig = new BlockFruit("fig");
		grapefruit = new BlockFruit("grapefruit");
		lemon = new BlockFruit("lemon");
		lime = new BlockFruit("lime");
		maple = new BlockFruitTree("maple");
		mango = new BlockFruit("mango");
		nutmeg = new BlockFruit("nutmeg");
		olive = new BlockFruit("olive");
		orange = new BlockFruit("orange");
		papaya = new BlockFruit("papaya");
		paperbark = new BlockFruitTree("paperbark");
		peach = new BlockFruit("peach");
		pear = new BlockFruit("pear");
		pecan = new BlockFruit("pecan");
		peppercorn = new BlockFruit("peppercorn");
		persimmon = new BlockFruit("persimmon");
		pistachio = new BlockFruit("pistachio");
		plum = new BlockFruit("plum");
		pomegranate = new BlockFruit("pomegranate");
		starfruit = new BlockFruit("starfruit");
		vanillaBean = new BlockFruit("vanillaBean");
		walnut = new BlockFruit("walnut");

		ModBlocks.registerBlock(apple);
		ModBlocks.registerBlock(almond);
		ModBlocks.registerBlock(apricot);
		ModBlocks.registerBlock(avocado);
		ModBlocks.registerBlock(banana);
		ModBlocks.registerBlock(cashew);
		ModBlocks.registerBlock(cherry);
		ModBlocks.registerBlock(chestnut);
		ModBlocks.registerBlock(cinnamon);
		ModBlocks.registerBlock(coconut);
		ModBlocks.registerBlock(date);
		ModBlocks.registerBlock(dragonfruit);
		ModBlocks.registerBlock(durian);
		ModBlocks.registerBlock(fig);
		ModBlocks.registerBlock(grapefruit);
		ModBlocks.registerBlock(lemon);
		ModBlocks.registerBlock(lime);
		ModBlocks.registerBlock(maple);
		ModBlocks.registerBlock(mango);
		ModBlocks.registerBlock(nutmeg);
		ModBlocks.registerBlock(olive);
		ModBlocks.registerBlock(orange);
		ModBlocks.registerBlock(papaya);
		ModBlocks.registerBlock(paperbark);
		ModBlocks.registerBlock(peach);
		ModBlocks.registerBlock(pear);
		ModBlocks.registerBlock(pecan);
		ModBlocks.registerBlock(peppercorn);
		ModBlocks.registerBlock(persimmon);
		ModBlocks.registerBlock(pistachio);
		ModBlocks.registerBlock(plum);
		ModBlocks.registerBlock(pomegranate);
		ModBlocks.registerBlock(starfruit);
		ModBlocks.registerBlock(vanillaBean);
		ModBlocks.registerBlock(walnut);

		// Sapling
		appleSapling = new BlockSapling("appleSapling");
		almondSapling = new BlockSapling("almondSapling");
		apricotSapling = new BlockSapling("apricotSapling");
		avocadoSapling = new BlockSapling("avocadoSapling");
		bananaSapling = new BlockSapling("bananaSapling");
		cashewSapling = new BlockSapling("cashewSapling");
		cherrySapling = new BlockSapling("cherrySapling");
		chestnutSapling = new BlockSapling("chestnutSapling");
		cinnamonSapling = new BlockSapling("cinnamonSapling");
		coconutSapling = new BlockSapling("coconutSapling");
		dateSapling = new BlockSapling("dateSapling");
		dragonfruitSapling = new BlockSapling("dragonfruitSapling");
		durianSapling = new BlockSapling("durianSapling");
		figSapling = new BlockSapling("figSapling");
		grapefruitSapling = new BlockSapling("grapefruitSapling");
		lemonSapling = new BlockSapling("lemonSapling");
		limeSapling = new BlockSapling("limeSapling");
		mapleSapling = new BlockSapling("mapleSapling");
		mangoSapling = new BlockSapling("mangoSapling");
		nutmegSapling = new BlockSapling("nutmegSapling");
		oliveSapling = new BlockSapling("oliveSapling");
		orangeSapling = new BlockSapling("orangeSapling");
		papayaSapling = new BlockSapling("papayaSapling");
		paperbarkSapling = new BlockSapling("paperbarkSapling");
		peachSapling = new BlockSapling("peachSapling");
		pearSapling = new BlockSapling("pearSapling");
		pecanSapling = new BlockSapling("pecanSapling");
		peppercornSapling = new BlockSapling("peppercornSapling");
		persimmonSapling = new BlockSapling("persimmonSapling");
		pistachioSapling = new BlockSapling("pistachioSapling");
		plumSapling = new BlockSapling("plumSapling");
		pomegranateSapling = new BlockSapling("pomegranateSapling");
		starfruitSapling = new BlockSapling("starfruitSapling");
		vanillaBeanSapling = new BlockSapling("vanillaBeanSapling");
		walnutSapling = new BlockSapling("walnutSapling");

		ModBlocks.registerBlock(appleSapling);
		ModBlocks.registerBlock(almondSapling);
		ModBlocks.registerBlock(apricotSapling);
		ModBlocks.registerBlock(avocadoSapling);
		ModBlocks.registerBlock(bananaSapling);
		ModBlocks.registerBlock(cashewSapling);
		ModBlocks.registerBlock(cherrySapling);
		ModBlocks.registerBlock(chestnutSapling);
		ModBlocks.registerBlock(cinnamonSapling);
		ModBlocks.registerBlock(coconutSapling);
		ModBlocks.registerBlock(dateSapling);
		ModBlocks.registerBlock(dragonfruitSapling);
		ModBlocks.registerBlock(durianSapling);
		ModBlocks.registerBlock(figSapling);
		ModBlocks.registerBlock(grapefruitSapling);
		ModBlocks.registerBlock(lemonSapling);
		ModBlocks.registerBlock(limeSapling);
		ModBlocks.registerBlock(mapleSapling);
		ModBlocks.registerBlock(mangoSapling);
		ModBlocks.registerBlock(nutmegSapling);
		ModBlocks.registerBlock(oliveSapling);
		ModBlocks.registerBlock(orangeSapling);
		ModBlocks.registerBlock(papayaSapling);
		ModBlocks.registerBlock(paperbarkSapling);
		ModBlocks.registerBlock(peachSapling);
		ModBlocks.registerBlock(pearSapling);
		ModBlocks.registerBlock(pecanSapling);
		ModBlocks.registerBlock(peppercornSapling);
		ModBlocks.registerBlock(persimmonSapling);
		ModBlocks.registerBlock(pistachioSapling);
		ModBlocks.registerBlock(plumSapling);
		ModBlocks.registerBlock(pomegranateSapling);
		ModBlocks.registerBlock(starfruitSapling);
		ModBlocks.registerBlock(vanillaBeanSapling);
		ModBlocks.registerBlock(walnutSapling);

		// Crop
		artichokeCrop = new BlockCrop("artichokeCrop");
		asparagusCrop = new BlockCrop("asparagusCrop");
		bambooShootCrop = new BlockCrop("bambooShootCrop");
		barleyCrop = new BlockCrop("barleyCrop");
		beanCrop = new BlockCrop("beanCrop");
		beetCrop = new BlockCrop("beetCrop");
		bellpepperCrop = new BlockCrop("bellpepperCrop");
		blackberryCrop = new BlockCrop("blackberryCrop");
		blueberryCrop = new BlockCrop("blueberryCrop");
		broccoliCrop = new BlockCrop("broccoliCrop");
		brusselSproutCrop = new BlockCrop("brusselSproutCrop");
		cabbageCrop = new BlockCrop("cabbageCrop");
		cactusFruitCrop = new BlockCrop("cactusFruitCrop");
		candleberryCrop = new BlockCrop("candleberryCrop");
		cantaloupeCrop = new BlockCrop("cantaloupeCrop");
		cauliflowerCrop = new BlockCrop("cauliflowerCrop");
		celeryCrop = new BlockCrop("celeryCrop");
		chilipepperCrop = new BlockCrop("chilipepperCrop");
		coffeeBeanCrop = new BlockCrop("coffeeBeanCrop");
		cornCrop = new BlockCrop("cornCrop");
		cottonCrop = new BlockCrop("cottonCrop");
		cranberryCrop = new BlockCrop("cranberryCrop");
		cucumberCrop = new BlockCrop("cucumberCrop");
		eggplantCrop = new BlockCrop("eggplantCrop");
		garlicCrop = new BlockCrop("garlicCrop");
		gingerCrop = new BlockCrop("gingerCrop");
		grapeCrop = new BlockCrop("grapeCrop");
		kiwiCrop = new BlockCrop("kiwiCrop");
		leekCrop = new BlockCrop("leekCrop");
		lettuceCrop = new BlockCrop("lettuceCrop");
		mustardSeedsCrop = new BlockCrop("mustardSeedsCrop");
		oatsCrop = new BlockCrop("oatsCrop");
		okraCrop = new BlockCrop("okraCrop");
		onionCrop = new BlockCrop("onionCrop");
		parsnipCrop = new BlockCrop("parsnipCrop");
		peanutCrop = new BlockCrop("peanutCrop");
		peasCrop = new BlockCrop("peasCrop");
		pineappleCrop = new BlockCrop("pineappleCrop");
		radishCrop = new BlockCrop("radishCrop");
		raspberryCrop = new BlockCrop("raspberryCrop");
		rhubarbCrop = new BlockCrop("rhubarbCrop");
		riceCrop = new BlockCrop("riceCrop");
		rutabagaCrop = new BlockCrop("rutabagaCrop");
		ryeCrop = new BlockCrop("ryeCrop");
		scallionCrop = new BlockCrop("scallionCrop");
		seaweedCrop = new BlockCrop("seaweedCrop");
		soybeanCrop = new BlockCrop("soybeanCrop");
		spiceLeafCrop = new BlockCrop("spiceLeafCrop");
		strawberryCrop = new BlockCrop("strawberryCrop");
		sweetPotatoCrop = new BlockCrop("sweetPotatoCrop");
		teaLeafCrop = new BlockCrop("teaLeafCrop");
		tomatoCrop = new BlockCrop("tomatoCrop");
		turnipCrop = new BlockCrop("turnipCrop");
		whiteMushroomCrop = new BlockCrop("whiteMushroomCrop");
		winterSquashCrop = new BlockCrop("winterSquashCrop");
		zucchiniCrop = new BlockCrop("zucchiniCrop");

		ModBlocks.registerBlock(artichokeCrop);
		ModBlocks.registerBlock(asparagusCrop);
		ModBlocks.registerBlock(bambooShootCrop);
		ModBlocks.registerBlock(barleyCrop);
		ModBlocks.registerBlock(beanCrop);
		ModBlocks.registerBlock(beetCrop);
		ModBlocks.registerBlock(bellpepperCrop);
		ModBlocks.registerBlock(blackberryCrop);
		ModBlocks.registerBlock(blueberryCrop);
		ModBlocks.registerBlock(broccoliCrop);
		ModBlocks.registerBlock(brusselSproutCrop);
		ModBlocks.registerBlock(cabbageCrop);
		ModBlocks.registerBlock(cactusFruitCrop);
		ModBlocks.registerBlock(candleberryCrop);
		ModBlocks.registerBlock(cantaloupeCrop);
		ModBlocks.registerBlock(cauliflowerCrop);
		ModBlocks.registerBlock(celeryCrop);
		ModBlocks.registerBlock(chilipepperCrop);
		ModBlocks.registerBlock(coffeeBeanCrop);
		ModBlocks.registerBlock(cornCrop);
		ModBlocks.registerBlock(cottonCrop);
		ModBlocks.registerBlock(cranberryCrop);
		ModBlocks.registerBlock(cucumberCrop);
		ModBlocks.registerBlock(eggplantCrop);
		ModBlocks.registerBlock(garlicCrop);
		ModBlocks.registerBlock(gingerCrop);
		ModBlocks.registerBlock(grapeCrop);
		ModBlocks.registerBlock(kiwiCrop);
		ModBlocks.registerBlock(leekCrop);
		ModBlocks.registerBlock(lettuceCrop);
		ModBlocks.registerBlock(mustardSeedsCrop);
		ModBlocks.registerBlock(oatsCrop);
		ModBlocks.registerBlock(okraCrop);
		ModBlocks.registerBlock(onionCrop);
		ModBlocks.registerBlock(parsnipCrop);
		ModBlocks.registerBlock(peanutCrop);
		ModBlocks.registerBlock(peasCrop);
		ModBlocks.registerBlock(pineappleCrop);
		ModBlocks.registerBlock(radishCrop);
		ModBlocks.registerBlock(raspberryCrop);
		ModBlocks.registerBlock(rhubarbCrop);
		ModBlocks.registerBlock(riceCrop);
		ModBlocks.registerBlock(rutabagaCrop);
		ModBlocks.registerBlock(ryeCrop);
		ModBlocks.registerBlock(scallionCrop);
		ModBlocks.registerBlock(seaweedCrop);
		ModBlocks.registerBlock(soybeanCrop);
		ModBlocks.registerBlock(spiceLeafCrop);
		ModBlocks.registerBlock(strawberryCrop);
		ModBlocks.registerBlock(sweetPotatoCrop);
		ModBlocks.registerBlock(teaLeafCrop);
		ModBlocks.registerBlock(tomatoCrop);
		ModBlocks.registerBlock(turnipCrop);
		ModBlocks.registerBlock(whiteMushroomCrop);
		ModBlocks.registerBlock(winterSquashCrop);
		ModBlocks.registerBlock(zucchiniCrop);

		// Candle
		candle_0 = new BlockCandle("candle_0", 0.9375F);
		candle_1 = new BlockCandle("candle_1", 0.9375F);
		candle_2 = new BlockCandle("candle_2", 0.9375F);
		candle_3 = new BlockCandle("candle_3", 0.9375F);
		candle_4 = new BlockCandle("candle_4", 0.9375F);
		candle_5 = new BlockCandle("candle_5", 0.9375F);
		candle_6 = new BlockCandle("candle_6", 0.9375F);
		candle_7 = new BlockCandle("candle_7", 0.9375F);
		candle_8 = new BlockCandle("candle_8", 0.9375F);
		candle_9 = new BlockCandle("candle_9", 0.9375F);
		candle_10 = new BlockCandle("candle_10", 0.9375F);
		candle_11 = new BlockCandle("candle_11", 0.9375F);
		candle_12 = new BlockCandle("candle_12", 0.9375F);
		candle_13 = new BlockCandle("candle_13", 0.9375F);
		candle_14 = new BlockCandle("candle_14", 0.9375F);
		candle_15 = new BlockCandle("candle_15", 0.9375F);

		ModBlocks.registerBlock(candle_0);
		ModBlocks.registerBlock(candle_1);
		ModBlocks.registerBlock(candle_2);
		ModBlocks.registerBlock(candle_3);
		ModBlocks.registerBlock(candle_4);
		ModBlocks.registerBlock(candle_5);
		ModBlocks.registerBlock(candle_6);
		ModBlocks.registerBlock(candle_7);
		ModBlocks.registerBlock(candle_8);
		ModBlocks.registerBlock(candle_9);
		ModBlocks.registerBlock(candle_10);
		ModBlocks.registerBlock(candle_11);
		ModBlocks.registerBlock(candle_12);
		ModBlocks.registerBlock(candle_13);
		ModBlocks.registerBlock(candle_14);
		ModBlocks.registerBlock(candle_15);

		temperateSaplings = new Block[] { appleSapling, avocadoSapling, cherrySapling, chestnutSapling, nutmegSapling,
				pearSapling, plumSapling, walnutSapling };

		warmSaplings = new Block[] { almondSapling, apricotSapling, bananaSapling, cashewSapling, coconutSapling,
				dateSapling, dragonfruitSapling, durianSapling, figSapling, grapefruitSapling, lemonSapling,
				limeSapling, mangoSapling, oliveSapling, orangeSapling, papayaSapling, peachSapling, pecanSapling,
				peppercornSapling, persimmonSapling, pistachioSapling, pomegranateSapling, starfruitSapling,
				vanillaBeanSapling };

		logSaplings = new Block[] { cinnamonSapling, mapleSapling, paperbarkSapling };
	}

	public static void registerBlock(final Block block) {
		GameRegistry.registerBlock(block, block.getUnlocalizedName().substring(5));
	}
}
